# Используем официальный образ postgre 11 версии

FROM postgres:13

ENV  POSTGRES_USER: lastparagon
ENV  POSTGRES_PASSWORD: sl-01
ENV  POSTGRES_DB: postgres

VOLUME [ "/var/lib/postgres/DE_course", "/var/lib/postgres/prom_data" ]
